[WIP] Generalize extensions
powsybl/powsybl-network-store-server pull request #23
Opened 2024-03-21 16:44 UTC by antoinebhs

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-04-05 14:07 UTC, geofjamg approved these changes

2024-04-08 14:16 UTC, FranckLecuyer requested changes

2024-04-08 14:32 UTC, FranckLecuyer requested changes

2024-04-08 14:32 UTC, FranckLecuyer commented on network-store-server/src/main/resources/db/changelog/changesets/migrationExtensions_20240306T120000Z.sql
> +               '"startup"'::jsonb
'"generatorstartup"' ?

2024-04-08 16:36 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/QueryExtensionCatalog.java
> +    public static String buildExtensionsQuery(String columnNameForWhereClause) {
You're right, thanks!
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/23/commits/99469abace51bec31ad788107691f2dc15fdf9af.

2024-04-09 07:13 UTC, FranckLecuyer approved these changes

2024-04-10 09:14 UTC, merged