add modify connectablePosition extension test
powsybl/powsybl-network-store-server pull request #58
Opened 2024-09-02 07:45 UTC by ghazwarhili

2024-09-02 09:26 UTC, FranckLecuyer requested changes

2024-09-02 09:26 UTC, FranckLecuyer commented on network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreExtensionsIT.java
> +            assertEquals(ConnectablePosition.Direction.BOTTOM, connectablePositionTwt3.getFeeder3().getDirection());
Here, you should flush the network with : service.flush(network);

And then add some code to reload the network and test that the extension modifications have successfully been made in database (see other test methods like  loadDetailExtensionTest, voltagePerReactivePowerControlTest, slackTerminalExtensionTest ...)

2024-09-04 07:20 UTC, FranckLecuyer requested changes

2024-09-04 07:20 UTC, FranckLecuyer commented on network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreExtensionsIT.java
> +            service.flush(readNetwork);
End the try block just after flush, and begin a new try block with the creation of a new NetworkStoreService object :
To be consistent with what is done in the other methods (cgmesExtensionsTest for example)

2024-09-04 13:05 UTC, FranckLecuyer approved these changes

2024-09-04 13:08 UTC, EtienneLt approved these changes

2024-10-21 15:45 UTC, closed without merging