upgrade network store server to v1.17.0
powsybl/powsybl-network-store-server pull request #59
Opened 2024-09-10 07:11 UTC by EtienneLt

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
no

**What kind of change does this PR introduce?**
dependencies upgrade

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

2024-09-10 08:33 UTC, FranckLecuyer requested changes

2024-09-10 08:33 UTC, FranckLecuyer commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
>                  //TODO : fix in network store should be ResourceType enum and not IdentifiableType
Remove comment

2024-09-12 15:33 UTC, SlimaneAmar approved these changes

2024-09-12 15:41 UTC, FranckLecuyer approved these changes

2024-09-12 15:43 UTC, merged