Support partial variants
powsybl/powsybl-network-store-server pull request #90
Opened 2024-12-31 15:50 UTC by antoinebhs

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
This PR adds support for partial variant clone.  
In the following, we'll use these terms:
* Full variant: A variant that includes all required identifiables and external attributes (e.g., reactive capability curves, temporary limits, etc.).
* Full clone: A clone from a partial or full variant to a full variant.
* Partial variant: A variant that contains only the identifiables and external attributes whose values differ from those in the full variant (or created identifiables/external attributes). To be fully defined, a partial variant must be associated with a full variant, which provides the non-updated identifiables and external attributes. A partial variant cannot exist independently of a full variant.
* a partial clone is a clone from a partial or full variant to a partial variant.

Note: the concept of partial variant as it is implemented assumes (as before) that when a variant is modified, all the "child" variants are deleted and need to be rebuilt. We'll see that we may need to do something to prevent using the "Unbuild" on a full variant node.

**What is the current behavior?**
When cloning a network, all the identifiables and external attributes (reactive capability curves, temporary limits, etc.) are cloned. It leads to long clone time and duplicates unnecessary data in the server.

**What is the new behavior (if this is a feature change)?**
We add support for partial clone to only save on the server created/updated identifiables or external attributes in partial variants.

The new behavior of the different actions in partial variant is:
* Clone
Full variant -> full variant: clone all the identifiables/external attributes of the source
Full variant -> partial variant: nothing is cloned
Partial variant -> partial variant: clone all the identifiables/external attributes of the source
Partial variant -> full variant: not implemented, see further work

Note: By default, when creating a network or cloning a network, the clone strategy is always set to partial. This means that if you have N1 with clone strategy full and you full clone it to N2, the clone strategy of N2 will be partial. I did it that way because I consider that full clone are a one time operation and should not be persisted for the next variants. This logic is applied in the server and cached client/buffered client too.

* For identifiable/external attributes creations
Similarly to what was done before, we insert the resources in the corresponding variant.

* For identifiable updates
We start by retrieving the IDs of existing identifiables in the variant. Next, we partition the identifiables into two: those that already exist in the variant and those that do not. For the identifiables that exist, we update as before. For those that do not exist, we create new identifiables in the variant.
(+1 select query compared with main)

* For external attributes updates
Similarly to what was done before for most external attributes (except regulating point that were homogenized), we delete the external attributes from the variant and reinsert them with updated value. If the updated value is empty, we insert a tombstoned for this external attributes. The tombstone is a way to make the difference between an external attributes that have not been updated in this variant and an external attributes that have been deleted or emptied (e.g for list). We cannot use updated identifiables ids in the variant as there are partial updates like updateSv that don't update external attributes. 
(+1 select query/+1 insert query compared with main for tombstones)

* For identifiable updates SV
We start by retrieving the IDs of existing identifiables in the variant. Next, we partition the identifiables into two: those that already exist in the variant and those that do not. For the identifiables that exist, we update SV as before. For those that do not exist, we fetch corresponding identifiables in the full variant, then update with SV values in memory, then insert updated SV identifiables. 
We do that because the resources are not complete in the case of SV updates: it only contains SV attributes and we can't directly insert them.
(+1 select query compared with main)

Note: I noticed when testing that update SV do not seem to be batched on main branch (1 update SV = 1 update execution in the database).

* For identifiable deletes
We remove the identifiable (and associated external attributes) from the variant and add a tombstone for this identifiable. The tombstone is added to ensure that we don't look for the identifiable in the full variant on reading identifiables or external attributes.
(+1 insert query compared with main for tombstones)

* For identifiable/external attributes reads
First, we retrieve the resources from the full variant. Then, we remove the resources that are either tombstoned or updated in the partial variant from the full variant's list. Next, we fetch the updated resources and add them to the ones retrieved from the full variant.
(+2 select query compared with main: tombstones and updated identifiables)

* Extensions
Extensions are a special type of external attributes as they can be lazy loaded in the identifiables (in the client cache). It means that we can never assume that an updated identifiable contains all the extensions (compared with what is stored on the server).
This needs some adjustments that are best described in the ExtensionHandler code. The main idea is that:
* we only update (delete/recreate) the extensions that are present in the updated identifiable. This is valid as updated identifiables don't contain deleted extensions as we can only remove extensions using the removeExtension() method that uses a separate endpoint.
* when removing an extension in the removeExtension endpoint, we add a tombstone for the corresponding extension
* for readings, it's almost the same as other external attributes except that there is a bit more "merge" logic because we manipulate maps

* Tombstones
Tombstones are never removed as it means "don't look in full variant for this resource". There is one tomsbtone table for each external attributes and one for all identifiable types.

* Performance
On a Stanway network:
|                                                            | main (ms)        | diff-variant (ms)|   |
|------------------------------------------------------------|------------------|------------------|---|
| Create 1000 lines                                          | 952,5            | 846,625          |   |
| Create 1000 generators                                     | 257,5            | 215,66           |   |
| Initial clone                                              | 6841             | 4                |   |
| First updateSv 1000 lines (=> insert in diff-variant)      | 65,125           | 64,625           |   |
| First updateSv 1000 generators (=> insert in diff-variant) | 60,6             | 79,3             |   |
| Get lines after loadflow                                   | 1639             | 1711             |   |
| Get generators after loadflow                              | 73               | 114              |   |
| UpdateSv 1000 lines                                        | 51,125           | 58               |   |
| UpdateSv 1000 generators                                   | 45,16            | 57,5             |   |
| First update 1000 lines (=> insert in diff-variant)        | 849              | 720              |   |
| First update 1000 generators                               | 1181             | 104              | ? |
| Update 1000 lines                                          | 680              | 65 [...]

2025-01-02 14:28 UTC, antoinebhs commented
Note, to discuss ? : discussing with Geoffroy, he thinks that we should have tombstoned columns in each identifiable entity (for identifiable tombstone as well as external attributes tombstones) instead of separate tables. 
With this, we could use a where clause to remove tombstoned resources in select. However, it means that we should clone the identifiable in the partial variant if we delete it and it does not exist in the partial variant. While with separate tables as now, we just add a row in the tombstone table, I forgot to mention this last point while discussing with him.

2025-01-03 16:45 UTC, antoinebhs commented
Maybe we want to move the code relative to partial variant in ExtensionHandler to PartialVariantUtils to have all in the same place? It would be consistent with identifiables and other external attributes.

2025-01-10 16:03 UTC, FranckLecuyer requested changes

2025-01-17 10:51 UTC, FranckLecuyer commented
Tests: OK

2025-01-20 15:58 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="clonestrategy" value="&quot;PARTIAL&quot;"/>
Unfortunately we have to use quote for enum (see https://github.com/powsybl/powsybl-network-store-server/issues/67)

2025-01-20 16:03 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +                    () -> getTombstonedIdentifiableIds(connection, networkUuid, variantNum),
I will take these comments into account!

2025-01-23 15:55 UTC, antoinebhs commented
Discussing with @jonenst, we decided that all clones should be partial in this first version so there is no need to have parameters to change the clone strategy or store the clone strategy in DB.
I will update the PR accordingly.

2025-01-29 08:55 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +                    () -> getTombstonedIdentifiableIds(connection, networkUuid, variantNum),
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/ba1219e8761b34c0fe5a333b03820e8e1e7a7bb4

2025-01-29 08:55 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +                    () -> getTombstonedIdentifiableIds(connection, networkUuid, variantNum),
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/ba1219e8761b34c0fe5a333b03820e8e1e7a7bb4

2025-01-29 08:56 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +                    () -> getTombstonedIdentifiableIds(connection, networkId, variantNum));
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/ba1219e8761b34c0fe5a333b03820e8e1e7a7bb4

2025-01-29 08:56 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +                    () -> getTombstonedIdentifiableIds(connection, networkId, variantNum));
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/ba1219e8761b34c0fe5a333b03820e8e1e7a7bb4

2025-02-03 13:54 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="clonestrategy" value="&quot;PARTIAL&quot;"/>
This part was removed as we removed the CloneStrategy for now.

2025-02-04 13:41 UTC, FranckLecuyer approved these changes

2025-02-04 14:23 UTC, jonenst commented on network-store-server/src/main/java/com/powsybl/network/store/server/ExtensionHandler.java
> +        Map<String, Set<String>> tombstonedExtensions = getTombstonedExtensions(connection, networkId, variantNum);
avoid loading all tombstones just to check for one ?

2025-02-05 14:07 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +        <createIndex indexName="tombstonedidentifiable_networkuuid_variantnum_idx" tableName="tombstonedidentifiable">
Don't think we need this index if we have the primary key that already has networkuuid, variantnum

2025-02-05 14:08 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
same, not needed index

2025-02-05 14:08 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
same not needed index

2025-02-05 14:09 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
same not needed index

2025-02-05 14:09 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
same not needed index

2025-02-05 14:10 UTC, jonenst commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
same not needed index

2025-02-06 13:53 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:53 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:53 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:54 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:54 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:54 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +            <column name="networkuuid"/>
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 13:54 UTC, antoinebhs commented on network-store-server/src/main/resources/db/changelog/changesets/changelog_20241104T120000Z.xml
> +        <createIndex indexName="tombstonedidentifiable_networkuuid_variantnum_idx" tableName="tombstonedidentifiable">
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/b0785aff72d6cfe51e0d6e1e5da35c9edf2694ea

2025-02-06 15:48 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/ExtensionHandler.java
> +        Map<String, Set<String>> tombstonedExtensions = getTombstonedExtensions(connection, networkId, variantNum);
Fixed in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/13981cc90833b404b8b65ad161df0e7f5fdd031c

2025-02-11 10:34 UTC, SlimaneAmar approved these changes

2025-02-11 14:26 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +    static List<String> getIdentifiablesIdsForVariant(Connection connection, UUID networkUuid, int variantNum) {
Accounted for in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/07357f3197f46345f936bfb9b7f14baca806706b

2025-02-11 14:26 UTC, antoinebhs commented on network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
> +    public void updateBranchesSv(UUID networkUuid, List<Resource<BranchSvAttributes>> resources, String tableName, TableMapping tableMapping) {
Accounted for in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/07357f3197f46345f936bfb9b7f14baca806706b

2025-02-11 14:26 UTC, antoinebhs commented on network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
> +            assertEquals(-1, networkAttributes.getFullVariantNum());
Accounted for in https://github.com/powsybl/powsybl-network-store-server/pull/90/commits/07357f3197f46345f936bfb9b7f14baca806706b

2025-02-12 09:06 UTC, merged